In [200]:
import warnings
warnings.filterwarnings('ignore')
import pickle
import pandas as pd
import numpy as np

## Training Data

In [201]:
df_model = pickle.load(open('/home/pabhijit/data/model_ready_train.pkl', "rb" ) )

In [202]:
df_model.shape

(1258605, 38)

In [203]:
df_model.head()

month_int  ncodpers       age  antiguedad     renta  \
2512427          5   1061260  0.192982    0.138211  0.013679   
2512428          5   1061283  0.175439    0.138211  0.005355   
2512429          5   1061284  0.192982    0.138211  0.004607   
2512430          5   1061336  0.184211    0.138211  0.002271   
2512431          5   1061286  0.236842    0.138211  0.003631   

         pais_residencia_0  sexo_0  ind_nuevo_0  tiprel_1mes_1  \
2512427                  1       0            1              1   
2512428                  1       0            1              1   
2512429                  1       0            1              1   
2512430                  1       0            1              1   
2512431                  1       1            1              1   

         canal_entrada_1  ...  ind_hip_fin_ult1  ind_plan_fin_ult1  \
2512427                1  ...                 0                  0   
2512428                1  ...                 0                  0   
2512429                1  ...                 0                  0   
2512430                1  ...                 0                  0   
2512431                1  ...                 0                  0   

         ind_pres_fin_ult1  ind_reca_fin_ult1  ind_tjcr_fin_ult1  \
2512427                  0                  0                  0   
2512428                  0                  0                  0   
2512429                  0                  0                  0   
2512430                  0                  0                  0   
2512431                  0                  0                  0   

         ind_valo_fin_ult1  ind_viv_fin_ult1  ind_nomina_ult1  \
2512427                  0                 0                0   
2512428                  0                 0                0   
2512429                  0                 0                0   
2512430                  0                 0                0   
2512431                  0                 0                0   

         ind_nom_pens_ult1  ind_recibo_ult1  
2512427                  0                0  
2512428                  0                0  
2512429                  0                0  
2512430                  0                0  
2512431                  0                0  

[5 rows x 38 columns]

In [204]:
df_model.columns

Index(['month_int', 'ncodpers', 'age', 'antiguedad', 'renta',
       'pais_residencia_0', 'sexo_0', 'ind_nuevo_0', 'tiprel_1mes_1',
       'canal_entrada_1', 'canal_entrada_0', 'cod_prov_28',
       'ind_actividad_cliente_0', 'segmento_1', 'ind_ahor_fin_ult1',
       'ind_aval_fin_ult1', 'ind_cco_fin_ult1', 'ind_cder_fin_ult1',
       'ind_cno_fin_ult1', 'ind_ctju_fin_ult1', 'ind_ctma_fin_ult1',
       'ind_ctop_fin_ult1', 'ind_ctpp_fin_ult1', 'ind_deco_fin_ult1',
       'ind_deme_fin_ult1', 'ind_dela_fin_ult1', 'ind_ecue_fin_ult1',
       'ind_fond_fin_ult1', 'ind_hip_fin_ult1', 'ind_plan_fin_ult1',
       'ind_pres_fin_ult1', 'ind_reca_fin_ult1', 'ind_tjcr_fin_ult1',
       'ind_valo_fin_ult1', 'ind_viv_fin_ult1', 'ind_nomina_ult1',
       'ind_nom_pens_ult1', 'ind_recibo_ult1'],
      dtype='object')

### Data - Month 5

In [205]:
df_month_5 = df_model[df_model['month_int']==5]
df_month_5 = df_month_5.add_suffix('_05')
df_month_5 = df_month_5.rename(columns={'ncodpers_05': 'ncodpers',
                                        'age_05' : 'age',
                                        'antiguedad_05' : 'antiguedad',
                                        'renta_05' : 'renta',
                                        'pais_residencia_0_05' : 'pais_residencia_0',
                                        'sexo_0_05' : 'sexo_0',
                                        'ind_nuevo_0_05' : 'ind_nuevo_0',
                                        'tiprel_1mes_1_05' : 'tiprel_1mes_1',
                                        'canal_entrada_1_05' : 'canal_entrada_1',
                                        'canal_entrada_0_05' : 'canal_entrada_0',
                                        'cod_prov_28_05' : 'cod_prov_28',
                                        'ind_actividad_cliente_0_05' : 'ind_actividad_cliente_0',
                                        'segmento_1_05' : 'segmento_1'
                                       })
df_month_5

month_int_05  ncodpers       age  antiguedad     renta  \
2512427             5   1061260  0.192982    0.138211  0.013679   
2512428             5   1061283  0.175439    0.138211  0.005355   
2512429             5   1061284  0.192982    0.138211  0.004607   
2512430             5   1061336  0.184211    0.138211  0.002271   
2512431             5   1061286  0.236842    0.138211  0.003631   
...               ...       ...       ...         ...       ...   
3144379             5    547712  0.403509    0.483740  0.004607   
3144380             5    547691  0.298246    0.483740  0.003078   
3144381             5   1399490  0.000000    0.008130  0.004482   
3144382             5     15889  0.473684    0.995935  0.011246   
3144383             5     15890  0.526316    1.000000  0.002432   

         pais_residencia_0  sexo_0  ind_nuevo_0  tiprel_1mes_1  \
2512427                  1       0            1              1   
2512428                  1       0            1              1   
2512429                  1       0            1              1   
2512430                  1       0            1              1   
2512431                  1       1            1              1   
...                    ...     ...          ...            ...   
3144379                  1       1            1              1   
3144380                  1       0            1              1   
3144381                  1       0            0              1   
3144382                  1       1            1              0   
3144383                  1       1            1              0   

         canal_entrada_1  ...  ind_hip_fin_ult1_05  ind_plan_fin_ult1_05  \
2512427                1  ...                    0                     0   
2512428                1  ...                    0                     0   
2512429                1  ...                    0                     0   
2512430                1  ...                    0                     0   
2512431                1  ...                    0                     0   
...                  ...  ...                  ...                   ...   
3144379                0  ...                    0                     0   
3144380                0  ...                    0                     0   
3144381                0  ...                    0                     0   
3144382                0  ...                    0                     0   
3144383                0  ...                    0                     1   

         ind_pres_fin_ult1_05  ind_reca_fin_ult1_05  ind_tjcr_fin_ult1_05  \
2512427                     0                     0                     0   
2512428                     0                     0                     0   
2512429                     0                     0                     0   
2512430                     0                     0                     0   
2512431                     0                     0                     0   
...                       ...                   ...                   ...   
3144379                     0                     0                     0   
3144380                     0                     0                     0   
3144381                     0                     0                     0   
3144382                     0                     0                     1   
3144383                     0                     0                     1   

         ind_valo_fin_ult1_05  ind_viv_fin_ult1_05  ind_nomina_ult1_05  \
2512427                     0                    0                   0   
2512428                     0                    0                   0   
2512429                     0                    0                   0   
2512430                     0                    0                   0   
2512431                     0                    0                   0   
...                       ...                  ...                 ...   
3144379                     0                    0     

### Data - Month 6

In [206]:
df_month_6 = df_model[df_model['month_int']==6]
df_month_6 = df_month_6.add_suffix('_06')
df_month_6 = df_month_6.rename(columns={'ncodpers_06': 'ncodpers',
                                        'age_06' : 'age',
                                        'antiguedad_06' : 'antiguedad',
                                        'renta_06' : 'renta',
                                        'pais_residencia_0_06' : 'pais_residencia_0',
                                        'sexo_0_06' : 'sexo_0',
                                        'ind_nuevo_0_06' : 'ind_nuevo_0',
                                        'tiprel_1mes_1_06' : 'tiprel_1mes_1',
                                        'canal_entrada_1_06' : 'canal_entrada_1',
                                        'canal_entrada_0_06' : 'canal_entrada_0',
                                        'cod_prov_28_06' : 'cod_prov_28',
                                        'ind_actividad_cliente_0_06' : 'ind_actividad_cliente_0',
                                        'segmento_1_06' : 'segmento_1'
                                       })
df_month_6

month_int_06  ncodpers       age  antiguedad     renta  \
3144384             6     16132  0.403509    0.991870  0.005527   
3144385             6   1063040  0.201754    0.138211  0.002544   
3144386             6   1063041  0.192982    0.138211  0.001172   
3144387             6   1063042  0.210526    0.138211  0.002464   
3144388             6   1063043  0.184211    0.138211  0.004607   
...               ...       ...       ...         ...       ...   
3776489             6    549679  0.324561    0.483740  0.007780   
3776490             6    549682  0.324561    0.483740  0.001170   
3776491             6    549673  0.412281    0.426829  0.002492   
3776492             6    889143  0.385965    0.239837  0.011230   
3776493             6    498639  0.552632    0.524390  0.004607   

         pais_residencia_0  sexo_0  ind_nuevo_0  tiprel_1mes_1  \
3144384                  1       1            1              0   
3144385                  1       1            1              0   
3144386                  1       0            1              0   
3144387                  1       0            1              1   
3144388                  1       1            1              1   
...                    ...     ...          ...            ...   
3776489                  1       1            1              1   
3776490                  1       1            1              1   
3776491                  1       0            1              0   
3776492                  1       0            1              0   
3776493                  1       1            1              0   

         canal_entrada_1  ...  ind_hip_fin_ult1_06  ind_plan_fin_ult1_06  \
3144384                0  ...                    0                     0   
3144385                1  ...                    0                     0   
3144386                1  ...                    0                     0   
3144387                1  ...                    0                     0   
3144388                1  ...                    0                     0   
...                  ...  ...                  ...                   ...   
3776489                0  ...                    0                     0   
3776490                0  ...                    0                     0   
3776491                0  ...                    0                     0   
3776492                0  ...                    0                     0   
3776493                0  ...                    0                     0   

         ind_pres_fin_ult1_06  ind_reca_fin_ult1_06  ind_tjcr_fin_ult1_06  \
3144384                     0                     0                     0   
3144385                     0                     0                     0   
3144386                     0                     0                     0   
3144387                     0                     0                     0   
3144388                     0                     0                     0   
...                       ...                   ...                   ...   
3776489                     0                     0                     0   
3776490                     0                     0                     0   
3776491                     0                     0                     0   
3776492                     0                     1                     1   
3776493                     0                     0                     0   

         ind_valo_fin_ult1_06  ind_viv_fin_ult1_06  ind_nomina_ult1_06  \
3144384                     0                    0                   0   
3144385                     0                    0                   0   
3144386                     0                    0                   0   
3144387                     0                    0                   0   
3144388                     0                    0                   0   
...                       ...                  ...                 ...   
3776489                     0                    0     

### Merge DFs

**NOTE** - Reason for joining the DFs is to take only those records which exist for both the months.

In [207]:
df_merge = pd.merge(df_month_5, df_month_6, on=['ncodpers'])
df_merge

month_int_05  ncodpers     age_x  antiguedad_x   renta_x  \
0                  5   1061260  0.192982      0.138211  0.013679   
1                  5   1061283  0.175439      0.138211  0.005355   
2                  5   1061284  0.192982      0.138211  0.004607   
3                  5   1061336  0.184211      0.138211  0.002271   
4                  5   1061286  0.236842      0.138211  0.003631   
...              ...       ...       ...           ...       ...   
626738             5    547712  0.403509      0.483740  0.004607   
626739             5    547691  0.298246      0.483740  0.003078   
626740             5   1399490  0.000000      0.008130  0.004482   
626741             5     15889  0.473684      0.995935  0.011246   
626742             5     15890  0.526316      1.000000  0.002432   

        pais_residencia_0_x  sexo_0_x  ind_nuevo_0_x  tiprel_1mes_1_x  \
0                         1         0              1                1   
1                         1         0              1                1   
2                         1         0              1                1   
3                         1         0              1                1   
4                         1         1              1                1   
...                     ...       ...            ...              ...   
626738                    1         1              1                1   
626739                    1         0              1                1   
626740                    1         0              0                1   
626741                    1         1              1                0   
626742                    1         1              1                0   

        canal_entrada_1_x  ...  ind_hip_fin_ult1_06  ind_plan_fin_ult1_06  \
0                       1  ...                    0                     0   
1                       1  ...                    0                     0   
2                       1  ...                    0                     0   
3                       1  ...                    0                     0   
4                       1  ...                    0                     0   
...                   ...  ...                  ...                   ...   
626738                  0  ...                    0                     0   
626739                  0  ...                    0                     0   
626740                  0  ...                    0                     0   
626741                  0  ...                    0                     0   
626742                  0  ...                    0                     1   

        ind_pres_fin_ult1_06  ind_reca_fin_ult1_06  ind_tjcr_fin_ult1_06  \
0                          0                     0                     0   
1                          0                     0                     0   
2                          0                     0                     0   
3                          0                     0                     0   
4                          0                     0                     0   
...                      ...                   ...                   ...   
626738                     0                     0                     0   
626739                     0                     0                     0   
626740                     0                     0                     0   
626741                     0                     0                     1   
626742                     0                     0                     1   

        ind_valo_fin_ult1_06  ind_viv_fin_ult1_06  ind_nomina_ult1_06  \
0                          0                    0                   0   
1                          0                    0                   0   
2                          0                    0                   0   
3                          0                    0                   0   
4                          0                    0                   0   
...                      ...          

In [208]:
df_merge.columns

Index(['month_int_05', 'ncodpers', 'age_x', 'antiguedad_x', 'renta_x',
       'pais_residencia_0_x', 'sexo_0_x', 'ind_nuevo_0_x', 'tiprel_1mes_1_x',
       'canal_entrada_1_x', 'canal_entrada_0_x', 'cod_prov_28_x',
       'ind_actividad_cliente_0_x', 'segmento_1_x', 'ind_ahor_fin_ult1_05',
       'ind_aval_fin_ult1_05', 'ind_cco_fin_ult1_05', 'ind_cder_fin_ult1_05',
       'ind_cno_fin_ult1_05', 'ind_ctju_fin_ult1_05', 'ind_ctma_fin_ult1_05',
       'ind_ctop_fin_ult1_05', 'ind_ctpp_fin_ult1_05', 'ind_deco_fin_ult1_05',
       'ind_deme_fin_ult1_05', 'ind_dela_fin_ult1_05', 'ind_ecue_fin_ult1_05',
       'ind_fond_fin_ult1_05', 'ind_hip_fin_ult1_05', 'ind_plan_fin_ult1_05',
       'ind_pres_fin_ult1_05', 'ind_reca_fin_ult1_05', 'ind_tjcr_fin_ult1_05',
       'ind_valo_fin_ult1_05', 'ind_viv_fin_ult1_05', 'ind_nomina_ult1_05',
       'ind_nom_pens_ult1_05', 'ind_recibo_ult1_05', 'month_int_06', 'age_y',
       'antiguedad_y', 'renta_y', 'pais_residencia_0_y', 'sexo_0_y',
       'ind_nue

In [209]:
# Remove redundant columns
df_merge = df_merge.drop(['month_int_05', 'month_int_06', 'month_int_06', 'age_y',
                           'antiguedad_y', 'renta_y', 'pais_residencia_0_y', 'sexo_0_y',
                           'ind_nuevo_0_y', 'tiprel_1mes_1_y', 'canal_entrada_1_y',
                           'canal_entrada_0_y', 'cod_prov_28_y', 'ind_actividad_cliente_0_y',
                           'segmento_1_y']
                         , axis=1)

df_merge = df_merge.rename(columns={'age_x' : 'age',
                                    'antiguedad_x' : 'antiguedad',
                                    'renta_x' : 'renta',
                                    'pais_residencia_0_x' : 'pais_residencia_0',
                                    'sexo_0_x' : 'sexo_0',
                                    'ind_nuevo_0_x' : 'ind_nuevo_0',
                                    'tiprel_1mes_1_x' : 'tiprel_1mes_1',
                                    'canal_entrada_1_x' : 'canal_entrada_1',
                                    'canal_entrada_0_x' : 'canal_entrada_0',
                                    'cod_prov_28_x' : 'cod_prov_28',
                                    'ind_actividad_cliente_0_x' : 'ind_actividad_cliente_0',
                                    'segmento_1_x' : 'segmento_1'
                                    })
df_merge

ncodpers       age  antiguedad     renta  pais_residencia_0  sexo_0  \
0        1061260  0.192982    0.138211  0.013679                  1       0   
1        1061283  0.175439    0.138211  0.005355                  1       0   
2        1061284  0.192982    0.138211  0.004607                  1       0   
3        1061336  0.184211    0.138211  0.002271                  1       0   
4        1061286  0.236842    0.138211  0.003631                  1       1   
...          ...       ...         ...       ...                ...     ...   
626738    547712  0.403509    0.483740  0.004607                  1       1   
626739    547691  0.298246    0.483740  0.003078                  1       0   
626740   1399490  0.000000    0.008130  0.004482                  1       0   
626741     15889  0.473684    0.995935  0.011246                  1       1   
626742     15890  0.526316    1.000000  0.002432                  1       1   

        ind_nuevo_0  tiprel_1mes_1  canal_entrada_1  canal_entrada_0  ...  \
0                 1              1                1                0  ...   
1                 1              1                1                0  ...   
2                 1              1                1                0  ...   
3                 1              1                1                0  ...   
4                 1              1                1                0  ...   
...             ...            ...              ...              ...  ...   
626738            1              1                0                0  ...   
626739            1              1                0                0  ...   
626740            0              1                0                0  ...   
626741            1              0                0                0  ...   
626742            1              0                0                0  ...   

        ind_hip_fin_ult1_06  ind_plan_fin_ult1_06  ind_pres_fin_ult1_06  \
0                         0                     0                     0   
1                         0                     0                     0   
2                         0                     0                     0   
3                         0                     0                     0   
4                         0                     0                     0   
...                     ...                   ...                   ...   
626738                    0                     0                     0   
626739                    0                     0                     0   
626740                    0                     0                     0   
626741                    0                     0                     0   
626742                    0                     1                     0   

        ind_reca_fin_ult1_06  ind_tjcr_fin_ult1_06  ind_valo_fin_ult1_06  \
0                          0                     0                     0   
1                          0                     0                     0   
2                          0                     0                     0   
3                          0                     0                     0   
4                          0                     0                     0   
...                      ...                   ...                   ...   
626738                     0                     0                     0   
626739                     0                     0                     0   
626740                     0                     0                     0   
626741                     0                     1                     1   
626742                     0                     1                     0   

        ind_viv_fin_ult1_06  ind_nomina_ult1_06  ind_nom_pens_ult1_06  \
0                         0                   0                     0   
1                         0                   0                     0   
2                         0                   0                     0   
3                         0 

### Create Arrays

- Create separate product matrix arrays. 
- Subtract prod_arr_5 from prod_arr_6 to get the new product matrix for month 6
- Reason for these arrays is for ease of operation.

In [210]:
df_merge.columns

Index(['ncodpers', 'age', 'antiguedad', 'renta', 'pais_residencia_0', 'sexo_0',
       'ind_nuevo_0', 'tiprel_1mes_1', 'canal_entrada_1', 'canal_entrada_0',
       'cod_prov_28', 'ind_actividad_cliente_0', 'segmento_1',
       'ind_ahor_fin_ult1_05', 'ind_aval_fin_ult1_05', 'ind_cco_fin_ult1_05',
       'ind_cder_fin_ult1_05', 'ind_cno_fin_ult1_05', 'ind_ctju_fin_ult1_05',
       'ind_ctma_fin_ult1_05', 'ind_ctop_fin_ult1_05', 'ind_ctpp_fin_ult1_05',
       'ind_deco_fin_ult1_05', 'ind_deme_fin_ult1_05', 'ind_dela_fin_ult1_05',
       'ind_ecue_fin_ult1_05', 'ind_fond_fin_ult1_05', 'ind_hip_fin_ult1_05',
       'ind_plan_fin_ult1_05', 'ind_pres_fin_ult1_05', 'ind_reca_fin_ult1_05',
       'ind_tjcr_fin_ult1_05', 'ind_valo_fin_ult1_05', 'ind_viv_fin_ult1_05',
       'ind_nomina_ult1_05', 'ind_nom_pens_ult1_05', 'ind_recibo_ult1_05',
       'ind_ahor_fin_ult1_06', 'ind_aval_fin_ult1_06', 'ind_cco_fin_ult1_06',
       'ind_cder_fin_ult1_06', 'ind_cno_fin_ult1_06', 'ind_ctju_fin_ult1_06',


In [211]:
# Convert dataframe into array
arr_x = np.array(df_merge[['ncodpers', 'age', 'antiguedad', 'renta', 'pais_residencia_0', 'sexo_0',
                           'ind_nuevo_0', 'tiprel_1mes_1', 'canal_entrada_1', 'canal_entrada_0',
                           'cod_prov_28', 'ind_actividad_cliente_0', 'segmento_1']])
print(arr_x[0])

[1.06126000e+06 1.92982456e-01 1.38211382e-01 1.36787928e-02
 1.00000000e+00 0.00000000e+00 1.00000000e+00 1.00000000e+00
 1.00000000e+00 0.00000000e+00 1.00000000e+00 1.00000000e+00
 0.00000000e+00]


In [212]:
arr_prod_5 = np.array(df_merge[['ind_ahor_fin_ult1_05', 'ind_aval_fin_ult1_05', 'ind_cco_fin_ult1_05',
                               'ind_cder_fin_ult1_05', 'ind_cno_fin_ult1_05', 'ind_ctju_fin_ult1_05',
                               'ind_ctma_fin_ult1_05', 'ind_ctop_fin_ult1_05', 'ind_ctpp_fin_ult1_05',
                               'ind_deco_fin_ult1_05', 'ind_deme_fin_ult1_05', 'ind_dela_fin_ult1_05',
                               'ind_ecue_fin_ult1_05', 'ind_fond_fin_ult1_05', 'ind_hip_fin_ult1_05',
                               'ind_plan_fin_ult1_05', 'ind_pres_fin_ult1_05', 'ind_reca_fin_ult1_05',
                               'ind_tjcr_fin_ult1_05', 'ind_valo_fin_ult1_05', 'ind_viv_fin_ult1_05',
                               'ind_nomina_ult1_05', 'ind_nom_pens_ult1_05', 'ind_recibo_ult1_05']])
print(arr_prod_5[0])

[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [213]:
arr_prod_6 = np.array(df_merge[['ind_ahor_fin_ult1_06', 'ind_aval_fin_ult1_06', 'ind_cco_fin_ult1_06',
                               'ind_cder_fin_ult1_06', 'ind_cno_fin_ult1_06', 'ind_ctju_fin_ult1_06',
                               'ind_ctma_fin_ult1_06', 'ind_ctop_fin_ult1_06', 'ind_ctpp_fin_ult1_06',
                               'ind_deco_fin_ult1_06', 'ind_deme_fin_ult1_06', 'ind_dela_fin_ult1_06',
                               'ind_ecue_fin_ult1_06', 'ind_fond_fin_ult1_06', 'ind_hip_fin_ult1_06',
                               'ind_plan_fin_ult1_06', 'ind_pres_fin_ult1_06', 'ind_reca_fin_ult1_06',
                               'ind_tjcr_fin_ult1_06', 'ind_valo_fin_ult1_06', 'ind_viv_fin_ult1_06',
                               'ind_nomina_ult1_06', 'ind_nom_pens_ult1_06', 'ind_recibo_ult1_06']])
print(arr_prod_6[0])

[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [214]:
# Subtract Arrays to get the new prod array
arr_prod_new = np.subtract(arr_prod_6, arr_prod_5)
arr_prod_new

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int8)

In [215]:
# Convert any negative values to 0
arr_prod_new[arr_prod_new < 0] = 0
arr_prod_new

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int8)

In [216]:
x_train = arr_x[:,1:13] # 1st element is Cust ID which is not a valid predictor
y_train = arr_prod_new

In [217]:
print(x_train)
print(y_train)

[[0.19298246 0.13821138 0.01367879 ... 1.         1.         0.        ]
 [0.1754386  0.13821138 0.00535472 ... 1.         1.         0.        ]
 [0.19298246 0.13821138 0.00460682 ... 0.         0.         0.        ]
 ...
 [0.         0.00813008 0.00448168 ... 0.         0.         0.        ]
 [0.47368421 0.99593496 0.01124562 ... 1.         0.         1.        ]
 [0.52631579 1.         0.00243168 ... 1.         0.         0.        ]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## Test Data

In [218]:
df_model_test = pickle.load(open('/home/pabhijit/data/santander_model_ready_test.pkl', "rb" ) )

In [219]:
df_model_test.shape

(929615, 14)

In [220]:
df_model_test.head()

month_int  ncodpers       age  antiguedad     renta  pais_residencia_0  \
0         18     15889  0.333333    0.996109  0.011246                  1   
1         18   1170544  0.209877    0.132296  0.004599                  1   
2         18   1170545  0.123457    0.132296  0.004599                  1   
3         18   1170547  0.123457    0.132296  0.005095                  1   
4         18   1170548  0.123457    0.132296  0.003658                  1   

   sexo_0  ind_nuevo_0  tiprel_1mes_1  canal_entrada_1  canal_entrada_0  \
0       1            1              0                0                0   
1       0            1              1                0                0   
2       1            1              0                1                0   
3       0            1              1                1                0   
4       0            1              1                1                0   

   cod_prov_28  ind_actividad_cliente_0  segmento_1  
0            1                        0           1  
1            0                        1           0  
2            0                        0           0  
3            0                        1           0  
4            0                        1           0

In [221]:
arr_test = np.array(df_model_test)
arr_test

array([[1.80000000e+01, 1.58890000e+04, 3.33333333e-01, ...,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [1.80000000e+01, 1.17054400e+06, 2.09876543e-01, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [1.80000000e+01, 1.17054500e+06, 1.23456790e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.80000000e+01, 6.60240000e+05, 3.08641975e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.80000000e+01, 6.60243000e+05, 1.85185185e-01, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [1.80000000e+01, 6.60248000e+05, 5.55555556e-01, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00]])

In [222]:
x_test = arr_test[:,2:14]
x_test[0]

array([0.33333333, 0.99610895, 0.01124562, 1.        , 1.        ,
       1.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 1.        ])

## Modeling

In [223]:
from sklearn.model_selection import train_test_split
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

In [224]:
# Fit an independent logistic regression model for each class using the
# OneVsRestClassifier wrapper.
base_lr = LogisticRegression()
ovr = OneVsRestClassifier(base_lr)
ovr.fit(x_train, y_train)

OneVsRestClassifier(estimator=LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='warn',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='warn', tol=0.0001,
                                                 verbose=0, warm_start=False),
                    n_jobs=None)

In [225]:
y_pred = ovr.predict(x_test)
y_pred

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [226]:
y_pred_prob = ovr.predict_proba(x_test)
y_pred_prob

array([[0.        , 0.        , 0.01461189, ..., 0.01955332, 0.0283367 ,
        0.02677046],
       [0.        , 0.        , 0.00357277, ..., 0.00032526, 0.00017663,
        0.00110883],
       [0.        , 0.        , 0.01924657, ..., 0.01366446, 0.01009646,
        0.0223774 ],
       ...,
       [0.        , 0.        , 0.02073093, ..., 0.01834164, 0.01902612,
        0.03181057],
       [0.        , 0.        , 0.00314245, ..., 0.00032968, 0.0001526 ,
        0.00137498],
       [0.        , 0.        , 0.0052235 , ..., 0.00029708, 0.00152581,
        0.00385762]])

In [227]:
print(y_pred[0])


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [228]:
print(y_pred_prob[0])

[0.00000000e+00 0.00000000e+00 1.46118896e-02 2.75414942e-05
 1.18900649e-03 7.36396550e-06 5.29126880e-05 4.14972019e-03
 1.59254968e-03 1.23192848e-05 5.15038474e-04 3.38360733e-03
 2.10491096e-03 2.37921943e-03 1.68164456e-05 9.67997088e-05
 4.42638246e-05 1.87742478e-02 5.29356105e-02 1.40139100e-03
 6.41736134e-06 1.95533178e-02 2.83366960e-02 2.67704563e-02]


In [229]:
#arr_test[:,0:1]
print(arr_test[0,1])
print(arr_test[1,1])

15889.0
1170544.0


In [230]:
arr_nocodpers = arr_test[:,1:2]
y_pred_join = np.concatenate((arr_nocodpers, y_pred_prob), axis=1)

In [231]:
y_pred_join[0]

array([1.58890000e+04, 0.00000000e+00, 0.00000000e+00, 1.46118896e-02,
       2.75414942e-05, 1.18900649e-03, 7.36396550e-06, 5.29126880e-05,
       4.14972019e-03, 1.59254968e-03, 1.23192848e-05, 5.15038474e-04,
       3.38360733e-03, 2.10491096e-03, 2.37921943e-03, 1.68164456e-05,
       9.67997088e-05, 4.42638246e-05, 1.87742478e-02, 5.29356105e-02,
       1.40139100e-03, 6.41736134e-06, 1.95533178e-02, 2.83366960e-02,
       2.67704563e-02])

### Get top five recommended products

In [232]:
arr_nocodpers = np.array(df_model_test['ncodpers'])
arr_nocodpers[0]

15889

In [233]:
list_product = ['ind_ahor_fin_ult1','ind_aval_fin_ult1', 'ind_cco_fin_ult1', 'ind_cder_fin_ult1',
                'ind_cno_fin_ult1', 'ind_ctju_fin_ult1', 'ind_ctma_fin_ult1', 'ind_ctop_fin_ult1', 
                'ind_ctpp_fin_ult1', 'ind_deco_fin_ult1','ind_deme_fin_ult1', 'ind_dela_fin_ult1',
                'ind_ecue_fin_ult1','ind_fond_fin_ult1', 'ind_hip_fin_ult1', 'ind_plan_fin_ult1',
                'ind_pres_fin_ult1', 'ind_reca_fin_ult1', 'ind_tjcr_fin_ult1','ind_valo_fin_ult1', 
                'ind_viv_fin_ult1', 'ind_nomina_ult1','ind_nom_pens_ult1', 'ind_recibo_ult1']

In [234]:
#arr_nocodpers = arr_test[:,1:2].astype(int)
arr_pred = []
for i in range(len(arr_nocodpers)):
#for i in range(5):
    nocodpers = arr_nocodpers[i]
    pred_prob = y_pred_prob[i]
    
    #print(str(nocodpers) + ' : ' + str(pred_prob))
    arr = np.argsort(pred_prob)
    #print(arr)
    
    arr_rev = arr[::-1] # Get the elements in reverse order.
    #print(arr_rev)
    
    arr_top5 = arr_rev[:5]
    #print(arr_top5)
    
    lst=''
    for j in range(len(arr_top5)):
        idx = arr_top5[j]
        lst = lst + str(list_product[idx]) + ' '
    
    #print(lst)
    #print(str(nocodpers) + ',' + lst)
    
    arr_pred.append(lst)

In [235]:
# Get Top Five
out_df = pd.DataFrame({'ncodpers':arr_nocodpers, 'added_products':arr_pred})
out_df.to_csv('test_predictions_top5.csv', index=False)

In [236]:
# Get Top one
#out_df = pd.DataFrame({'ncodpers':arr_nocodpers, 'added_products':arr_pred[0].split()[0]})
#out_df.to_csv('test_predictions_top1.csv', index=False)

## Next Steps

- Study 5th place solution "santander_prod.py" and "santander_preprocess.py"
- Apply "LAG" logic, get all the data (not just 05 and 06 months data)
- Check the date variables, split into year/month/day and see if those could be valid predictors.
- Verify if Predictions makes any sense.
- Create separate notebook for Data Visualization and analysis.
- Merge train and test data prep steps via generic functions.

Verify other Algorithms  
- DecisionTree, Gradient Boost as base learner
- Classifier Chain
